//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoaMai
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIHOC()
        {
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
        }
    
        public string MABAIHOC { get; set; }
        public string TENBAIHOC { get; set; }
        public Nullable<int> SOTIET { get; set; }
        public string YEUCAUVEDUNGCU { get; set; }
        public string MAKHOI { get; set; }
        public string MAMON { get; set; }
    
        public virtual KHOI KHOI { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
    }
}
