//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoaMai
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public string MAHOCSINH { get; set; }
        public string TENHOCSINH { get; set; }
        public Nullable<int> DIEM { get; set; }
    }
}
