//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoaMai
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIKHOABIEU
    {
        public string MABAIHOC { get; set; }
        public string MALOP { get; set; }
        public string THU { get; set; }
        public Nullable<int> SOTHUTUTIET { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual BAIHOC BAIHOC { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
